# Generated by Django 2.0 on 2018-01-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_passwordforgotrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Já existe uma conta com esse email.'}, max_length=254, unique=True),
        ),
    ]
