export const tasksConstants = {
    FETCH_TODOTASKS_REQUEST: 'FETCH_TODOTASKS_REQUEST',
    FETCH_TODOTASKS_SUCCESS: 'FETCH_TODOTASKS_SUCCESS',
    FETCH_TODOTASKS_FAILURE: 'FETCH_TODOTASKS_FAILURE',
    UPDATE_TASK_REQUEST:     'UPDATE_TASK_REQUEST',
    UPDATE_TASK_SUCCESS:     'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAILURE:     'UPDATE_TASK_FAILURE',
};
