export const tasksConstants = {
    FETCH_TODOTASKS_REQUEST: 'FETCH_TODOTASKS_REQUEST',
    FETCH_TODOTASKS_SUCCESS: 'FETCH_TODOTASKS_SUCCESS',
    FETCH_TODOTASKS_FAILURE: 'FETCH_TODOTASKS_FAILURE'
};
