export const todoListConstants = {
    FETCH_TODOLISTS_REQUEST: 'FETCH_TODOLISTS_REQUEST',
    FETCH_TODOLISTS_SUCCESS: 'FETCH_TODOLISTS_SUCCESS',
    FETCH_TODOLISTS_FAILURE: 'FETCH_TODOLISTS_FAILURE',
};
